# Generated by Django 3.1.7 on 2021-04-05 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_month', models.IntegerField()),
                ('b_year', models.IntegerField()),
                ('b_starting', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_type', models.IntegerField(choices=[(1, 'Income'), (2, 'Expense')])),
                ('c_monthly', models.FloatField()),
                ('c_planned', models.FloatField()),
                ('c_notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_description', models.CharField(max_length=50)),
                ('t_amount', models.FloatField()),
                ('t_cleared', models.BooleanField()),
                ('t_month', models.IntegerField()),
                ('t_year', models.IntegerField()),
                ('t_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.categories')),
            ],
        ),
    ]
